# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               Yating Han
tagline:             ECE @ Carnegie Mellon
description:         I am seinor (technically master) studying Electrical and Computer Engineering at CMU.  
url:                 http://yatinghan.github.io
baseurl:             ''
paginate:            5
paginate_path:       "/blog/page:num/"

# Plugins, Tags, Categories and Analytics  
plugins:          [jekyll-paginate]

# About/contact
author:
  name:              Yating Han
  url:               http://yatinghan.github.io
  github:            https://github.com/yatinghan
  linkedin:          https://www.linkedin.com/in/yatinghan/